# Generated by Django 4.1.7 on 2023-02-18 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_taskstatus_alter_task_waiting_for_alter_task_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='taskstatus',
            table='kanban_task_statuses',
        ),
    ]
