# Generated by Django 4.1.7 on 2023-02-18 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_taskstatus_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('name', models.CharField(max_length=48, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'kanban_ticket_statuses',
            },
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticketstatus'),
        ),
    ]
