# Generated by Django 4.1.7 on 2023-02-18 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profession_alter_user_profession'),
        ('tickets', '0005_ticketstatus_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='waiting_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profession'),
        ),
    ]
