# Generated by Django 4.1.7 on 2023-02-17 19:12

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phone_field.models.PhoneField(max_length=31, unique=True),
        ),
    ]
