# Generated by Django 4.1.7 on 2023-02-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(choices=[('ЭЛЕКТРИК', 'Electrician')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Администратор', 'Admin'), ('Рабочий', 'Worker'), ('Гость', 'Guest')], default='Гость', max_length=32),
        ),
    ]
