# Generated by Django 4.1.7 on 2023-02-18 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_photo_alter_user_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='profession',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.profession'),
            preserve_default=False,
        ),
    ]
